application: codeigniter-appengine
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:

- url: /assets/js/*
  static_dir: assets/js

- url: /assets/css/*
  static_dir: assets/css

- url: /assets/images/*
  static_dir: assets/images

- url: /
  script: index.php

- url: /(.+)
  script: index.php
